package sep.view.viewcontroller;

import sep.view.json.               RDefaultServerRequestParser;
import sep.view.clientcontroller.   EGameState;
import sep.view.clientcontroller.   EClientInformation;
import sep.                         Types;
import sep.view.lib.                EGamePhase;
import sep.view.lib.                RRegisterCard;

import org.json.                    JSONObject;
import org.apache.logging.log4j.    LogManager;
import org.apache.logging.log4j.    Logger;
import java.util.                   ArrayList;
import java.util.                   Arrays;
import java.util.                   Objects;

/** Mocking Game View with no server connection required. */
public final class MockViewLauncher implements IMockView
{
    private static final Logger l = LogManager.getLogger(MockViewLauncher.class);

    private static final int    MOCK_PLAYER_COUNT      = 6;
    /** Due to JFX error on Sonoma 14.x.x. */
    private static final int    INIT_TIMEOUT_OSX       = 7_000;
    private static final int    INIT_TIMEOUT_OTHER     = 1_000;

    public MockViewLauncher()
    {
        super();
        return;
    }

    public void run()
    {
        EClientInformation.INSTANCE.setMockView(true);
        final Thread t = new Thread(() ->
        {
            l.info("Mock view started. Waiting for JavaFX thread to start.");
            try
            {
                // TODO
                //      We only need this for OSX, as the JavaFX thread is not started immediately.
                //      This is a current issue with JavaFX on Sonoma (14.x.x upwards)
                //      and only fixed in newer JFX Versions.
                if (Types.EOS.isOSX())
                {
                    Thread.sleep(MockViewLauncher.INIT_TIMEOUT_OSX);
                }
                else
                {
                    Thread.sleep(MockViewLauncher.INIT_TIMEOUT_OTHER);
                }
            }
            catch (InterruptedException e)
            {
                l.error("Interrupted while waiting for JavaFX thread to start.");
                return;
            }
            l.info("Give mock information to JavaFX thread.");

            /* Players */
            for (int i = 0; i < MockViewLauncher.MOCK_PLAYER_COUNT; i++)
            {
                EGameState.addRemotePlayer(new RDefaultServerRequestParser(new JSONObject(String.format("{\"messageType\":\"PlayerAdded\",\"messageBody\":{\"clientID\": %d,\"name\":\"Player %d\", \"figure\": %d}}", i, i, i))));
                continue;
            }

            // region Course creation

            /* Course */

            // final DefaultServerRequestParser dsrp = new DefaultServerRequestParser(new JSONObject("{\"messageType\":\"GameStarted\",\"messageBody\":{\"gameMap\":[[[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"right\"],\"type\":\"Antenna\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"top\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"bottom\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}]],[[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"StartA\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"StartA\",\"speed\":2}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}]],[[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"top\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"top\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"bottom\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"top\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"left\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"RestartPoint\",\"isOnBoard\":\"5B\",\"orientations\":[\"bottom\"]}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"left\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"right\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"right\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"top\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"bottom\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"bottom\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"bottom\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}]],[[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"count\":1,\"type\":\"CheckPoint\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]]]}}"));
            final RDefaultServerRequestParser dsrp = new RDefaultServerRequestParser(new JSONObject("{\"messageType\":\"GameStarted\",\"messageBody\":{\"gameMap\":[[[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"right\"],\"type\":\"Antenna\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"top\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"bottom\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"StartPoint\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}]],[[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"StartA\",\"speed\":1}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"StartA\"}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"StartA\",\"speed\":1}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}]],[[{\"orientations\":[\"bottom\",\"top\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"bottom\",\"top\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"bottom\",\"top\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"bottom\",\"top\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"bottom\",\"top\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"bottom\",\"top\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"bottom\",\"top\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"bottom\",\"top\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"right\",\"top\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"orientations\":[\"bottom\",\"top\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"top\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"top\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"bottom\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"top\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"bottom\"],\"type\":\"RestartPoint\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"left\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"right\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"top\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"},{\"orientations\":[\"bottom\"],\"count\":1,\"type\":\"Laser\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"bottom\"],\"type\":\"Wall\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"right\",\"bottom\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}]],[[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"right\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\",\"left\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"top\",\"bottom\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}]],[[{\"count\":1,\"type\":\"EnergySpace\",\"isOnBoard\":\"5B\"}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"orientations\":[\"left\",\"right\"],\"type\":\"ConveyorBelt\",\"isOnBoard\":\"5B\",\"speed\":2}],[{\"count\":1,\"type\":\"CheckPoint\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}],[{\"type\":\"Empty\",\"isOnBoard\":\"5B\"}]]]}}"));

            // region Legacy Course

//            DefaultServerRequestParser dsrp = new DefaultServerRequestParser(new JSONObject()
//                .put("messageType", "GameStarted")
//                .put("messageBody", new JSONObject().put("gameMap", new JSONArray()
//                    .put(new JSONArray() /* Rank one */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "A")
//                                .put("speed", 1)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "EnergySpace")
//                                .put("isOnBoard", "5B")
//                                .put("count", 1)
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank two */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "StartPoint")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("top").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right"))
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank three */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "A")
//                                .put("orientations", new JSONArray().put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "EnergySpace")
//                                .put("isOnBoard", "5B")
//                                .put("count", 1)
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom").put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("left").put("right"))
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank four */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "StartPoint")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "RestartPoint")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "CheckPoint")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank five */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Antenna")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "StartPoint")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "A")
//                                .put("orientations", new JSONArray().put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "EnergySpace")
//                                .put("isOnBoard", "5B")
//                                .put("count", 1)
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank six */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "StartPoint")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "A")
//                                .put("orientations", new JSONArray().put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "EnergySpace")
//                                .put("isOnBoard", "5B")
//                                .put("count", 1)
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank seven */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "StartPoint")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("right"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "5B")
//                                .put("orientations", new JSONArray().put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank eight */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Wall")
//                                .put("isOnBoard", "A")
//                                .put("orientations", new JSONArray().put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("bottom").put("left").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "EnergySpace")
//                                .put("isOnBoard", "5B")
//                                .put("count", 1)
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank nine */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "StartPoint")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left").put("top"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("right").put("left").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("left").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                    )
//                    .put(new JSONArray() /* Rank ten */
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "A")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "A")
//                                .put("speed", 1)
//                                .put("orientations", new JSONArray().put("right").put("left"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "EnergySpace")
//                                .put("isOnBoard", "5B")
//                                .put("count", 1)
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                            .put(new JSONObject()
//                                .put("type", "ConveyorBelt")
//                                .put("isOnBoard", "5B")
//                                .put("speed", 2)
//                                .put("orientations", new JSONArray().put("top").put("bottom"))
//                            )
//                        )
//                        .put(new JSONArray()
//                                .put(new JSONObject()
//                                .put("type", "Empty")
//                                .put("isOnBoard", "5B")
//                            )
//                        )
//                    )
//                )
//            ));

            // endregion Legacy Course

            // endregion Course creation

            EGameState.INSTANCE.setCurrentServerCourseJSON(dsrp.getGameCourse());
            ViewSupervisor.updateCourseView();
            EGameState.INSTANCE.setCurrentPhase(EGamePhase.PROGRAMMING);
            final String[] mockPCards = new String[] {"MoveI", "MoveI", "MoveI", "MoveII", "MoveII", "MoveII", "MoveIII", "MoveIII", "MoveIII"};
            for (final String s : mockPCards)
            {
                EGameState.INSTANCE.addGotRegister(s);
                continue;
            }
            EGameState.INSTANCE.setCurrentPlayer(0, false);

            for (int i = 0; i < 5; i++)
            {
                EGameState.INSTANCE.addRCardsToRemotes(new RRegisterCard[]{new RRegisterCard(0, "MoveI"), new RRegisterCard(1, "MoveI"), new RRegisterCard(2, "MoveI"), new RRegisterCard(3, "MoveII"), new RRegisterCard(4, "MoveII"), new RRegisterCard(5, "MoveII"), });
                continue;
            }

            EClientInformation.INSTANCE.setPlayerID(0);

//            EGameState.INSTANCE.refillShop(new ArrayList<String>(Arrays.asList("AdminPrivilege", "RearLaser", "MemorySwap", "SpamBlocker", "AdminPrivilege", "RearLaser")));
//            EGameState.INSTANCE.exchangeShop(new ArrayList<String>(Arrays.asList("AdminPrivilege", null)));

//            EGameState.INSTANCE.onUpgradeCardBought(0, "AdminPrivilege");
//            EGameState.INSTANCE.onUpgradeCardBought(0, "SpamBlocker");
//            EGameState.INSTANCE.onUpgradeCardBought(1, "RearLaser");

            EGameState.INSTANCE.getBoughtUpgradeCards()[3] = "AdminPrivilege";
            EGameState.INSTANCE.getBoughtUpgradeCards()[4] = "RearLaser";
            EGameState.INSTANCE.getBoughtUpgradeCards()[0] = "MemorySwap";
            EGameState.INSTANCE.getBoughtUpgradeCards()[1] = "SpamBlocker";

            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(0)).getBoughtUpgradeCards().add("AdminPrivilege");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(0)).getBoughtUpgradeCards().add("RearLaser");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(0)).getBoughtUpgradeCards().add("MemorySwap");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(0)).getBoughtUpgradeCards().add("SpamBlocker");

            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(2)).getBoughtUpgradeCards().add("RearLaser");

            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(3)).getBoughtUpgradeCards().add("AdminPrivilege");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(3)).getBoughtUpgradeCards().add("RearLaser");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(3)).getBoughtUpgradeCards().add("MemorySwap");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(3)).getBoughtUpgradeCards().add("SpamBlocker");

            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(4)).getBoughtUpgradeCards().add("RearLaser");

            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(5)).getBoughtUpgradeCards().add("AdminPrivilege");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(5)).getBoughtUpgradeCards().add("RearLaser");
            Objects.requireNonNull(EGameState.INSTANCE.getRemotePlayerByPlayerID(5)).getBoughtUpgradeCards().add("MemorySwap");

            ViewSupervisor.updatePlayerInformationArea();

//            ViewSupervisor.createShopDialogLater();

            ViewSupervisor.centerGameCourseLater();

            l.debug("Mock view ready.");

            return;
        });

        t.start();

        ViewSupervisor.run();

        l.info("Mock view killed.");

        return;
    }

}
