package sep.view.viewcontroller;

import sep.view.json.DefaultServerRequestParser;
import sep.view.clientcontroller.EGameState;
import sep.view.clientcontroller.RemotePlayer;
import sep.view.clientcontroller.EClientInformation;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.json.JSONObject;
import org.json.JSONArray;

/** Mocking Game View with no server connection required. */
public final class MockViewLauncher
{
    private static final Logger l = LogManager.getLogger(MockViewLauncher.class);

    private static final int MOCK_PLAYER_COUNT = 6;

    private MockViewLauncher() throws RuntimeException
    {
        super();
        l.error("This class cannot be instantiated.");
        throw new RuntimeException("This class cannot be instantiated.");
    }

    public static void run()
    {
        EClientInformation.INSTANCE.setMockView(true);
        Thread t = new Thread(() ->
        {
            l.info("Mock view started. Waiting for JavaFX thread to start.");
            try
            {
                Thread.sleep(1000);
            }
            catch (InterruptedException e)
            {
                l.error("Interrupted while waiting for JavaFX thread to start.");
                return;
            }
            l.info("Give mock information to JavaFX thread.");

            /* Players */
            for (int i = 0; i < MockViewLauncher.MOCK_PLAYER_COUNT; i++)
            {
                DefaultServerRequestParser dsrp = new DefaultServerRequestParser(new JSONObject(String.format(
                        "{\"messageType\":\"PlayerAdded\",\"messageBody\":{\"clientID\": %d,\"name\":\"Player %d\", \"figure\": %d}}", i, i, i
                )));
                EGameState.addRemotePlayer(dsrp);
            }

            // region Course creation

            /* Course */
            DefaultServerRequestParser dsrp = new DefaultServerRequestParser(new JSONObject()
                .put("messageType", "GameStarted")
                .put("messageBody", new JSONObject().put("gameMap", new JSONArray()
                    .put(new JSONArray() /* Rank one */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "A")
                                .put("speed", 1)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "EnergySpace")
                                .put("isOnBoard", "5B")
                                .put("count", 1)
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank two */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "StartPoint")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("top").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right"))
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank three */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "A")
                                .put("orientations", new JSONArray().put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "EnergySpace")
                                .put("isOnBoard", "5B")
                                .put("count", 1)
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom").put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("left").put("right"))
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank four */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "StartPoint")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "RestartPoint")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "CheckPoint")
                                .put("isOnBoard", "5B")
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank five */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Antenna")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "StartPoint")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "A")
                                .put("orientations", new JSONArray().put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "EnergySpace")
                                .put("isOnBoard", "5B")
                                .put("count", 1)
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank six */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "StartPoint")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "A")
                                .put("orientations", new JSONArray().put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "EnergySpace")
                                .put("isOnBoard", "5B")
                                .put("count", 1)
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank seven */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "StartPoint")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("right"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "5B")
                                .put("orientations", new JSONArray().put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank eight */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Wall")
                                .put("isOnBoard", "A")
                                .put("orientations", new JSONArray().put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("bottom").put("left").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "EnergySpace")
                                .put("isOnBoard", "5B")
                                .put("count", 1)
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank nine */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "StartPoint")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left").put("top"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("right").put("left").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("left").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                    )
                    .put(new JSONArray() /* Rank ten */
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "A")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "A")
                                .put("speed", 1)
                                .put("orientations", new JSONArray().put("right").put("left"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "EnergySpace")
                                .put("isOnBoard", "5B")
                                .put("count", 1)
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                            .put(new JSONObject()
                                .put("type", "ConveyorBelt")
                                .put("isOnBoard", "5B")
                                .put("speed", 2)
                                .put("orientations", new JSONArray().put("top").put("bottom"))
                            )
                        )
                        .put(new JSONArray()
                                .put(new JSONObject()
                                .put("type", "Empty")
                                .put("isOnBoard", "5B")
                            )
                        )
                    )
                )
            ));

            // endregion Course creation

            EGameState.INSTANCE.setCurrentServerCourseJSON(dsrp.getGameCourse());
            ViewLauncher.updateCourseView();
            EGameState.INSTANCE.setCurrentPhase(0);
            EGameState.INSTANCE.setCurrentPlayer(0);

            return;
        });

        t.start();

        ViewLauncher.run();

        l.info("Mock view killed.");

        return;
    }

}
